<?php
// $Id$

/**
 * @file
 * Provides an interface to add/edit/remote Google Ad paths.
 */

require_once dirname(__FILE__) . '/google_admanager_path.inc';

/**
 * Implements hook_init().
 */
function google_admanager_path_init() {
  global $user;
  
  $query_path = substr(drupal_get_path_alias($_SERVER['REQUEST_URI']), 1);
  
  foreach ( google_admanager_path_get_paths_by_rule($query_path) as $path ) {
    if ( user_access('view google admanager path status') && isset($user->google_admanager_path_messages) && $user->google_admanager_path_messages ) {
      drupal_set_message( t('Advertisement Critera: !tag -> !name', array('!tag' => $path->tag, '!name' => $path->name)) );
    }
    google_admanager_add_attribute($path->tag, $path->name);
  }
}

/**
 * Implements hook_perm().
 */
function google_admanager_path_perm() {
  return array('administer google admanager path', 'view google admanager path status');
}

/**
 * Implements hook_menu().
 */
function google_admanager_path_menu() {
  return array(
    'admin/content/advertisement' => array(
      'title' => 'Advertisements',
      'description' => 'Administer advertisements',
      'page callback' => 'google_admanager_path_admin',
      'access arguments' => array('administer google admanager path'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'google_admanager_path.admin.inc',
    ),
    'admin/content/advertisement/list' => array(
      'title' => 'List',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => 0,
    ),
    'admin/content/advertisement/add' => array(
      'title' => 'Add',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('google_admanager_path_form'),
      'access arguments' => array('administer google admanager path'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'google_admanager_path.admin.inc',
      'weight' => 1,
    ),
    'admin/content/advertisement/edit/%google_admanager_path' => array(
      'title' => 'Edit',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('google_admanager_path_form', 4),
      'access arguments' => array('administer google admanager path'),
      'type' => MENU_CALLBACK,
      'file' => 'google_admanager_path.admin.inc',
      'weight' => 1,
    ),
  );
}

/**
 * Implements hook_user().
 */
function google_admanager_path_user($op, &$edit, &$account, $category = NULL) {
  if ( $op == 'form' && $category == 'account' && user_access('view google admanager path status', $account) ) {
    $form['google_admanager_path'] = array(
      '#type' => 'fieldset',
      '#title' => t('Google Admanager'),
      '#collapsible' => TRUE,
      '#weight' => -9,
    );
    
    $form['google_admanager_path']['google_admanager_path_messages'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable Google Admanager Messages'),
      '#default_value' => isset($account->google_admanager_path_messages) ? $account->google_admanager_path_messages : 0,
    );
    
    return $form;
  }
}

/**
 * Implements hook_theme().
 */
function google_admanager_path_theme($existing, $type, $theme, $path) {
  return array(
    'google_admanager_path_admin_form' => array(
      'arguments' => array('form' => NULL),
      'file' => 'google_admanager_path.admin.inc',
    ),
  );
}
